# PostgreSQL Exporter for Database Monitoring
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-exporter
  namespace: f1-analytics
  labels:
    app: postgres-exporter
    component: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-exporter
  template:
    metadata:
      labels:
        app: postgres-exporter
        component: monitoring
    spec:
      containers:
      - name: postgres-exporter
        image: prometheuscommunity/postgres-exporter:v0.13.2
        ports:
        - containerPort: 9187
          name: metrics
        env:
        - name: DATA_SOURCE_NAME
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: exporter-data-source-name
        - name: PG_EXPORTER_WEB_LISTEN_ADDRESS
          value: "0.0.0.0:9187"
        - name: PG_EXPORTER_EXTEND_QUERY_PATH
          value: "/etc/postgres_exporter/queries.yaml"
        volumeMounts:
        - name: postgres-exporter-config
          mountPath: /etc/postgres_exporter
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /metrics
            port: 9187
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /metrics
            port: 9187
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: postgres-exporter-config
        configMap:
          name: postgres-exporter-config
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-exporter
  namespace: f1-analytics
  labels:
    app: postgres-exporter
    component: monitoring
spec:
  selector:
    app: postgres-exporter
  ports:
  - port: 9187
    targetPort: 9187
    name: metrics
  type: ClusterIP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-exporter-config
  namespace: f1-analytics
  labels:
    app: postgres-exporter
    component: monitoring
data:
  queries.yaml: |
    # F1 Analytics specific PostgreSQL queries
    f1_race_data_freshness:
      query: "SELECT extract(epoch from (now() - max(created_at))) as seconds_since_last_race_update FROM races"
      master: true
      metrics:
        - seconds_since_last_race_update:
            usage: "GAUGE"
            description: "Seconds since last race data update"

    f1_prediction_count:
      query: "SELECT count(*) as total_predictions FROM predictions WHERE created_at >= now() - interval '24 hours'"
      master: true
      metrics:
        - total_predictions:
            usage: "GAUGE"
            description: "Total predictions generated in last 24 hours"

    f1_accuracy_metrics:
      query: |
        SELECT
          model_type,
          avg(accuracy_score) as avg_accuracy,
          count(*) as prediction_count
        FROM prediction_accuracy
        WHERE calculated_at >= now() - interval '7 days'
        GROUP BY model_type
      master: true
      metrics:
        - avg_accuracy:
            usage: "GAUGE"
            description: "Average prediction accuracy by model type"
            labels:
              - model_type
        - prediction_count:
            usage: "GAUGE"
            description: "Number of predictions by model type"
            labels:
              - model_type

    f1_database_size:
      query: |
        SELECT
          schemaname,
          tablename,
          pg_total_relation_size(schemaname||'.'||tablename) as size_bytes
        FROM pg_tables
        WHERE schemaname = 'public'
      master: true
      metrics:
        - size_bytes:
            usage: "GAUGE"
            description: "Size of database tables in bytes"
            labels:
              - schemaname
              - tablename
---
# Redis Exporter for Cache Monitoring
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-exporter
  namespace: f1-analytics
  labels:
    app: redis-exporter
    component: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-exporter
  template:
    metadata:
      labels:
        app: redis-exporter
        component: monitoring
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9121"
    spec:
      containers:
      - name: redis-exporter
        image: oliver006/redis_exporter:v1.54.0
        ports:
        - containerPort: 9121
          name: metrics
        env:
        - name: REDIS_ADDR
          value: "redis://redis-service:6379"
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis-secret
              key: password
        - name: REDIS_EXPORTER_WEB_LISTEN_ADDRESS
          value: "0.0.0.0:9121"
        - name: REDIS_EXPORTER_LOG_FORMAT
          value: "json"
        resources:
          requests:
            memory: "32Mi"
            cpu: "25m"
          limits:
            memory: "64Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /metrics
            port: 9121
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /metrics
            port: 9121
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: redis-exporter
  namespace: f1-analytics
  labels:
    app: redis-exporter
    component: monitoring
spec:
  selector:
    app: redis-exporter
  ports:
  - port: 9121
    targetPort: 9121
    name: metrics
  type: ClusterIP
---
# Node Exporter DaemonSet for Host Metrics
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-exporter
  namespace: f1-analytics
  labels:
    app: node-exporter
    component: monitoring
spec:
  selector:
    matchLabels:
      app: node-exporter
  template:
    metadata:
      labels:
        app: node-exporter
        component: monitoring
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9100"
    spec:
      hostNetwork: true
      hostPID: true
      containers:
      - name: node-exporter
        image: prom/node-exporter:v1.6.1
        args:
          - '--path.procfs=/host/proc'
          - '--path.sysfs=/host/sys'
          - '--path.rootfs=/host/root'
          - '--collector.filesystem.ignored-mount-points=^/(dev|proc|sys|var/lib/docker/.+)($|/)'
          - '--collector.filesystem.ignored-fs-types=^(autofs|binfmt_misc|cgroup|configfs|debugfs|devpts|devtmpfs|fusectl|hugetlbfs|mqueue|overlay|proc|procfs|pstore|rpc_pipefs|securityfs|sysfs|tracefs)$'
        ports:
        - containerPort: 9100
          name: metrics
          hostPort: 9100
        volumeMounts:
        - name: proc
          mountPath: /host/proc
          readOnly: true
        - name: sys
          mountPath: /host/sys
          readOnly: true
        - name: root
          mountPath: /host/root
          readOnly: true
        resources:
          requests:
            memory: "32Mi"
            cpu: "25m"
          limits:
            memory: "64Mi"
            cpu: "200m"
        securityContext:
          runAsNonRoot: true
          runAsUser: 65534
      volumes:
      - name: proc
        hostPath:
          path: /proc
      - name: sys
        hostPath:
          path: /sys
      - name: root
        hostPath:
          path: /
      tolerations:
      - effect: NoSchedule
        operator: Exists
---
# Blackbox Exporter for External Endpoint Monitoring
apiVersion: v1
kind: ConfigMap
metadata:
  name: blackbox-exporter-config
  namespace: f1-analytics
  labels:
    app: blackbox-exporter
    component: monitoring
data:
  blackbox.yml: |
    modules:
      http_2xx:
        prober: http
        timeout: 5s
        http:
          valid_status_codes: [200, 201, 202]
          method: GET
          follow_redirects: true
          preferred_ip_protocol: "ip4"

      http_post_2xx:
        prober: http
        timeout: 5s
        http:
          valid_status_codes: [200, 201, 202]
          method: POST

      tcp_connect:
        prober: tcp
        timeout: 5s

      dns:
        prober: dns
        timeout: 5s
        dns:
          query_name: "f1-analytics.example.com"
          query_type: "A"

      icmp:
        prober: icmp
        timeout: 5s

      # F1 Analytics specific probes
      f1_api_health:
        prober: http
        timeout: 10s
        http:
          valid_status_codes: [200]
          method: GET
          headers:
            User-Agent: "blackbox-exporter/f1-analytics"
          body: ""

      ergast_api:
        prober: http
        timeout: 15s
        http:
          valid_status_codes: [200]
          method: GET
          headers:
            User-Agent: "f1-analytics-monitoring"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blackbox-exporter
  namespace: f1-analytics
  labels:
    app: blackbox-exporter
    component: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blackbox-exporter
  template:
    metadata:
      labels:
        app: blackbox-exporter
        component: monitoring
    spec:
      containers:
      - name: blackbox-exporter
        image: prom/blackbox-exporter:v0.24.0
        args:
          - '--config.file=/config/blackbox.yml'
        ports:
        - containerPort: 9115
          name: metrics
        volumeMounts:
        - name: blackbox-config
          mountPath: /config
        resources:
          requests:
            memory: "32Mi"
            cpu: "25m"
          limits:
            memory: "64Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /metrics
            port: 9115
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /metrics
            port: 9115
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: blackbox-config
        configMap:
          name: blackbox-exporter-config
---
apiVersion: v1
kind: Service
metadata:
  name: blackbox-exporter
  namespace: f1-analytics
  labels:
    app: blackbox-exporter
    component: monitoring
spec:
  selector:
    app: blackbox-exporter
  ports:
  - port: 9115
    targetPort: 9115
    name: metrics
  type: ClusterIP